# Generated by Django 5.1.3 on 2024-11-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_phonenumberverification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumberverification',
            name='activated_referal_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
